[package]
name = "reth-blockchain-tree"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# reth
reth-primitives.workspace = true
reth-interfaces.workspace = true
reth-db.workspace = true
reth-provider.workspace = true
reth-stages-api.workspace = true
reth-trie = { workspace = true, features = ["metrics"] }
reth-trie-parallel = { workspace = true, features = ["parallel"] }
reth-consensus.workspace = true

# common
parking_lot.workspace = true
lru = "0.12"
tracing.workspace = true
tokio = { workspace = true, features = ["macros", "sync"] }

# metrics
reth-metrics = { workspace = true, features = ["common"] }
metrics.workspace = true

# misc
aquamarine.workspace = true
linked_hash_set = "0.1.4"

[dev-dependencies]
reth-db = { workspace = true, features = ["test-utils"] }
reth-interfaces = { workspace = true, features = ["test-utils"] }
reth-primitives = { workspace = true , features = ["test-utils"] }
reth-provider = { workspace = true, features = ["test-utils"] }
reth-revm.workspace = true
reth-node-ethereum.workspace = true
parking_lot.workspace = true
assert_matches.workspace = true

[features]
test-utils = []
optimism = ["reth-primitives/optimism", "reth-interfaces/optimism", "reth-provider/optimism", "reth-revm/optimism"]
