[package]
name = "reth-interfaces"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
reth-primitives.workspace = true
reth-fs-util.workspace = true
reth-consensus.workspace = true
reth-network-types.workspace = true

reth-network-api = { workspace = true, optional = true }
reth-eth-wire-types = { workspace = true, optional = true }

# async
futures = { workspace = true, optional = true }
tokio = { workspace = true, features = ["sync"], optional = true }

# misc
auto_impl.workspace = true
thiserror.workspace = true
tracing = { workspace = true, optional = true }
secp256k1 = { workspace = true, default-features = false, features = [
    "alloc",
    "recovery",
    "rand",
], optional = true }
clap = { workspace = true, features = ["derive"], optional = true }
parking_lot = { workspace = true, optional = true }
rand = { workspace = true, optional = true }

[dev-dependencies]
reth-consensus = { workspace = true, features = ["test-utils"] }

parking_lot.workspace = true
rand.workspace = true
tokio = { workspace = true, features = ["full"] }
secp256k1 = { workspace = true, features = ["alloc", "recovery", "rand"] }

[features]
default = []
p2p = ["reth-network-api", "reth-eth-wire-types", "tracing", "tokio", "futures" ]
test-utils = ["reth-consensus/test-utils", "secp256k1", "rand", "parking_lot"]
cli = ["clap"]
optimism = ["reth-eth-wire-types/optimism"]
