[package]
name = "reth-stages-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# reth
reth-primitives.workspace = true
reth-provider.workspace = true
reth-db.workspace = true
reth-interfaces.workspace = true
reth-static-file.workspace = true
reth-tokio-util.workspace = true
reth-consensus.workspace = true

# metrics
reth-metrics.workspace = true
metrics.workspace = true

# async
tokio = { workspace = true, features = ["sync"] }
tokio-stream.workspace = true
futures-util.workspace = true

# misc
aquamarine.workspace = true
thiserror.workspace = true
tracing.workspace = true
auto_impl.workspace = true

[dev-dependencies]
assert_matches.workspace = true
reth-provider = { workspace = true, features = ["test-utils"] }
reth-interfaces = { workspace = true, features = ["test-utils"] }

[features]
test-utils = []
