[package]
name = "reth-evm-optimism"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# Reth
reth-evm.workspace = true
reth-primitives.workspace = true
reth-revm.workspace = true
reth-interfaces.workspace = true
reth-provider.workspace = true

# Optimism
revm-primitives.workspace = true

# misc
tracing.workspace = true

[dev-dependencies]
reth-revm = { workspace = true, features = ["test-utils"] }

[features]
optimism = [
    "reth-primitives/optimism",
    "reth-provider/optimism",
    "reth-revm/optimism",
    "reth-interfaces/optimism",
    "revm-primitives/optimism",
]
