[package]
name = "reth-network-types"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Network types and utils"

[lints]
workspace = true

[dependencies]

# eth
alloy-primitives = { workspace = true, features = ["rlp"] }
alloy-rlp = { workspace = true, features = ["derive"] }
enr.workspace = true
tokio = { workspace = true, features = ["sync"] }

# crypto
secp256k1.workspace = true

# misc
serde_with.workspace = true
thiserror.workspace = true
url.workspace = true

[dev-dependencies]
alloy-primitives = { workspace = true, features = ["rand"] }
rand.workspace = true
secp256k1 = { workspace = true, features = ["rand"] }
serde_json.workspace = true
